# Context Bus Configuration - Federated Context Exchange
# Version: 1.0.0

version: "1.0.0"
last_updated: "2025-10-30T00:00:00Z"

# ============================================================================
# STORAGE BACKEND
# ============================================================================
storage:
  # Primary storage for embeddings
  primary:
    type: "pgvector"  # or "pinecone", "weaviate", "qdrant", "faiss"
    config:
      host: "${DB_HOST:-localhost}"
      port: 5432
      database: "${DB_NAME:-orca_mesh}"
      user: "${DB_USER:-postgres}"
      password: "${DB_PASSWORD:-}"
      ssl_mode: "require"
      pool_size: 20
      max_overflow: 10
      table_name: "context_embeddings"
      dimension: 1536  # OpenAI ada-002 dimension
      
  # Cache layer
  cache:
    enabled: true
    type: "redis"
    config:
      host: "${REDIS_HOST:-localhost}"
      port: 6379
      password: "${REDIS_PASSWORD:-}"
      db: 0
      ttl_seconds: 3600  # 1 hour
      max_memory: "1gb"
      eviction_policy: "allkeys-lru"
      
  # Backup storage
  backup:
    enabled: true
    type: "s3"
    config:
      bucket: "${S3_BUCKET:-orca-context-backup}"
      region: "${AWS_REGION:-us-east-1}"
      prefix: "context-embeddings/"
      retention_days: 90

# ============================================================================
# EMBEDDING CONFIGURATION
# ============================================================================
embeddings:
  # Provider
  provider: "openai"  # or "anthropic", "cohere", "huggingface", "custom"
  
  # Model configuration
  model:
    name: "text-embedding-ada-002"
    dimension: 1536
    max_tokens: 8191
    batch_size: 100
    
  # API configuration
  api:
    endpoint: "${OPENAI_API_ENDPOINT:-https://api.openai.com/v1}"
    api_key: "${OPENAI_API_KEY:-}"
    timeout_seconds: 30
    retry_attempts: 3
    
  # Caching
  cache:
    enabled: true
    ttl_seconds: 86400  # 24 hours
    key_prefix: "emb:"

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================
search:
  # Similarity search
  similarity:
    algorithm: "cosine"  # or "euclidean", "dot_product"
    threshold: 0.75  # Minimum similarity score
    max_results: 10
    
  # Hybrid search (combines semantic + keyword)
  hybrid:
    enabled: true
    semantic_weight: 0.7
    keyword_weight: 0.3
    
  # Filtering
  filters:
    enabled: true
    filterable_fields:
      - "agent_id"
      - "tenant_id"
      - "classification"
      - "created_at"
      - "tags"
      
  # Ranking
  ranking:
    enabled: true
    factors:
      - name: "recency"
        weight: 0.2
      - name: "relevance"
        weight: 0.6
      - name: "trust_score"
        weight: 0.2

# ============================================================================
# DEDUPLICATION
# ============================================================================
deduplication:
  enabled: true
  strategy: "near_duplicate"  # or "exact_duplicate", "semantic_duplicate"
  
  # Near-duplicate detection
  near_duplicate:
    threshold: 0.95  # Cosine similarity threshold
    window_hours: 24  # Check duplicates within this window
    action: "skip"  # or "merge", "replace"
    
  # Content hashing
  content_hash:
    enabled: true
    algorithm: "sha256"
    store_hash: true

# ============================================================================
# CONTEXT FEDERATION
# ============================================================================
federation:
  enabled: true
  
  # Multi-agent context sharing
  sharing:
    mode: "opt-in"  # or "opt-out"
    default_scope: "tenant"  # or "global", "private"
    access_control:
      enabled: true
      require_permission: true
      
  # Context propagation
  propagation:
    enabled: true
    max_hops: 3  # Prevent infinite propagation
    ttl_seconds: 3600
    
  # Cross-tenant isolation
  isolation:
    enabled: true
    strict_mode: true
    allow_cross_tenant: false  # Requires explicit permission

# ============================================================================
# SYNC POLICIES
# ============================================================================
sync:
  # Real-time sync
  real_time:
    enabled: true
    protocol: "websocket"  # or "sse", "polling"
    reconnect:
      enabled: true
      max_attempts: 5
      backoff_seconds: 5
      
  # Batch sync
  batch:
    enabled: true
    interval_seconds: 300  # 5 minutes
    batch_size: 1000
    compression: "gzip"
    
  # Conflict resolution
  conflict_resolution:
    strategy: "last_write_wins"  # or "manual_review", "merge"
    version_tracking: true
    audit_trail: true

# ============================================================================
# CONTEXT FRESHNESS
# ============================================================================
freshness:
  # Staleness detection
  staleness:
    enabled: true
    threshold_hours: 24
    action: "refresh"  # or "warn", "delete"
    
  # Auto-refresh
  auto_refresh:
    enabled: true
    interval_hours: 6
    priority_contexts: true  # Refresh high-priority contexts first
    
  # Expiration
  expiration:
    enabled: true
    default_ttl_days: 30
    min_ttl_hours: 1
    max_ttl_days: 365

# ============================================================================
# SECURITY
# ============================================================================
security:
  # Encryption at rest
  encryption_at_rest:
    enabled: true
    algorithm: "aes-256-gcm"
    key_provider: "aws_kms"
    key_id: "${KMS_KEY_ID:-}"
    
  # Encryption in transit
  encryption_in_transit:
    enabled: true
    tls_version: "1.3"
    
  # Access control
  access_control:
    enabled: true
    default_policy: "deny"
    require_authentication: true
    require_authorization: true
    
  # Data classification
  classification:
    enabled: true
    enforce_labels: true
    levels:
      - "public"
      - "internal"
      - "confidential"
      - "restricted"
      - "critical"
      
  # PII protection
  pii_protection:
    enabled: true
    auto_detect: true
    auto_redact: true
    audit_access: true

# ============================================================================
# PERFORMANCE
# ============================================================================
performance:
  # Connection pooling
  connection_pool:
    min_connections: 5
    max_connections: 50
    idle_timeout_seconds: 300
    
  # Query optimization
  query:
    use_index: true
    index_type: "ivfflat"  # or "hnsw" for pgvector
    lists: 100  # For IVFFlat index
    probes: 10  # For IVFFlat search
    
  # Batch processing
  batch:
    enabled: true
    max_batch_size: 1000
    batch_timeout_ms: 100
    
  # Caching strategy
  caching:
    strategy: "write-through"  # or "write-back", "write-around"
    warm_up: true
    preload_popular: true

# ============================================================================
# MONITORING
# ============================================================================
monitoring:
  # Metrics
  metrics:
    enabled: true
    metrics:
      - "context_bus.embeddings.total"
      - "context_bus.search.duration"
      - "context_bus.cache.hit_rate"
      - "context_bus.sync.lag"
      - "context_bus.deduplication.rate"
      
  # Health checks
  health_checks:
    enabled: true
    interval_seconds: 30
    checks:
      - "storage_connectivity"
      - "cache_connectivity"
      - "embedding_api_status"
      
  # Alerts
  alerts:
    enabled: true
    thresholds:
      cache_hit_rate_low: 0.5  # Alert if < 50%
      sync_lag_high_seconds: 300  # Alert if > 5 min
      storage_usage_high: 0.85  # Alert if > 85%

# ============================================================================
# QUOTAS AND LIMITS
# ============================================================================
quotas:
  # Per-tenant quotas
  per_tenant:
    max_embeddings: 1000000
    max_searches_per_day: 100000
    max_storage_gb: 10
    
  # Per-agent quotas
  per_agent:
    max_embeddings: 100000
    max_searches_per_hour: 10000
    
  # Rate limiting
  rate_limits:
    embeddings_per_second: 100
    searches_per_second: 1000
    
  # Resource limits
  resource_limits:
    max_dimension: 2048
    max_text_length: 100000
    max_metadata_size_kb: 10

# ============================================================================
# ADVANCED FEATURES
# ============================================================================
advanced:
  # Multi-modal support
  multi_modal:
    enabled: false
    types:
      - "text"
      - "image"
      - "audio"
      
  # Knowledge graph integration
  knowledge_graph:
    enabled: false
    provider: "neo4j"
    
  # Temporal context
  temporal:
    enabled: true
    track_versions: true
    max_versions: 10
    
  # Collaborative filtering
  collaborative_filtering:
    enabled: false
    algorithm: "user-based"
