name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type/bug", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below with as much detail as possible.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System down or data loss
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic
    validations:
      required: true
  
  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the system is affected?
      multiple: true
      options:
        - Agent Registry
        - Trust Scoring (UADSI)
        - Policy Engine
        - API/Gateway
        - Telemetry/Observability
        - Security
        - UI/Frontend
        - Database/Supabase
        - Deployment/Vercel
        - Documentation
        - Other
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - Node version: [e.g., 18.18.0]
        - ORCA version: [e.g., 1.0.0]
        - Browser (if UI bug): [e.g., Chrome 120, Firefox 121]
        - Deployment: [e.g., local, staging, production]
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Paste any relevant logs, error messages, or stack traces
      render: shell
      placeholder: Paste logs here (please redact any sensitive information)
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste image URLs
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, workarounds, or related issues
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have redacted any sensitive information (API keys, passwords, etc.)
          required: true
        - label: This issue contains a minimal reproducible example
          required: false
