name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type/feature", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or pain point this feature would solve
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
        Users are asking for...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        I would like to be able to...
        The system should...
        Add a feature that...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Another approach could be...
        I also considered...
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocking usage
        - High - Important for core workflows
        - Medium - Nice to have
        - Low - Future enhancement
    validations:
      required: true
  
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the system would this feature affect?
      multiple: true
      options:
        - Agent Registry
        - Trust Scoring (UADSI)
        - Policy Engine
        - API/Gateway
        - Telemetry/Observability
        - Security
        - UI/Frontend
        - Database/Supabase
        - Deployment/Vercel
        - Documentation
        - DevEx/Tooling
        - Other
    validations:
      required: true
  
  - type: textarea
    id: users
    attributes:
      label: User Impact
      description: Who would benefit from this feature and how?
      placeholder: |
        - Developers: ...
        - Operators: ...
        - End users: ...
        - Business stakeholders: ...
    validations:
      required: true
  
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] User can ...
        - [ ] System validates ...
        - [ ] Documentation includes ...
        - [ ] Tests cover ...
  
  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation notes
      placeholder: |
        - May require changes to...
        - Should integrate with...
        - Consider performance impact...
  
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Add any mockups, wireframes, diagrams, or examples
      placeholder: Drag and drop images here or paste URLs
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
        - label: I am willing to contribute to the implementation
          required: false
