/**
 * Report Engine - UADSI Core
 * Generates MD/CSV/PDF reports including executive summaries
 */

import { createLogger } from '@/common/logger';
import { TrustKPIs } from '@/common/types';
import { trustScoringEngine } from './trust-scoring';
import { syncAnalyzer } from './sync-analyzer';
import { agentDiscovery } from './agent-discovery';
import { agentRegistry } from '@/registry';
import * as fs from 'fs/promises';
import * as path from 'path';

const logger = createLogger('uadsi-report-engine');

export interface ReportConfig {
  format: 'markdown' | 'csv' | 'json';
  outputDir: string;
  includeSections: string[];
}

/**
 * Report Engine
 * Generates comprehensive reports
 */
export class ReportEngine {
  private outputDir: string;

  constructor(outputDir: string = './reports') {
    this.outputDir = outputDir;
  }

  /**
   * Generate executive summary
   */
  async generateExecutiveSummary(periodStart: Date, periodEnd: Date): Promise<string> {
    logger.info('Generating executive summary', { period_start: periodStart, period_end: periodEnd });

    // Gather data
    const kpis = await trustScoringEngine.computeTrustKPIs(periodStart, periodEnd);
    const syncFreshness = syncAnalyzer.getSyncFreshnessPercent();
    const driftRate = syncAnalyzer.getDriftRatePercent();
    const { agents, total } = await agentRegistry.query({ limit: 1000 });
    const stats = await agentRegistry.getStats();
    const discoveryStats = agentDiscovery.getStats();

    // Generate markdown
    const report = `# ORCA Executive Summary

**Period**: ${this.formatDate(periodStart)} to ${this.formatDate(periodEnd)}  
**Generated**: ${this.formatDate(new Date())}

---

## Key Performance Indicators

### Trust Score (TS)
**${kpis.trust_score}** / 100

The overall trust score across all registered agents. Scores above 80 indicate high trust and reliability.

### Risk Avoided (RA$)
**$${kpis.risk_avoided_usd.toLocaleString()}**

Estimated financial risk avoided through proactive monitoring, policy enforcement, and self-healing mechanisms.

### Return on Investment (ROI)
**${kpis.roi.toFixed(2)}x**

Platform ROI calculated as Risk Avoided ÷ Platform Cost. A healthy ROI indicates the platform is delivering significant value.

---

## Operational Metrics

| Metric | Value | Status |
|--------|-------|--------|
| Sync Freshness | ${syncFreshness.toFixed(1)}% | ${syncFreshness > 90 ? '✅ Good' : syncFreshness > 75 ? '⚠️ Fair' : '🔴 Poor'} |
| Drift Rate | ${driftRate.toFixed(1)}% | ${driftRate < 5 ? '✅ Low' : driftRate < 15 ? '⚠️ Moderate' : '🔴 High'} |
| Compliance SLA | ${kpis.compliance_sla_percent.toFixed(1)}% | ${kpis.compliance_sla_percent > 95 ? '✅ Met' : '⚠️ At Risk'} |
| Self-Resolution Ratio | ${(kpis.self_resolution_ratio * 100).toFixed(1)}% | ${kpis.self_resolution_ratio > 0.8 ? '✅ Excellent' : '⚠️ Needs Improvement'} |

---

## Agent Inventory

**Total Registered Agents**: ${total}

### By Status
${Object.entries(stats.by_status).map(([status, count]) => `- **${status}**: ${count}`).join('\n')}

### By Type
${Object.entries(stats.by_type).map(([type, count]) => `- **${type}**: ${count}`).join('\n')}

### Discovery Summary
- **Total Discovered**: ${discoveryStats.total_discovered}
- **Quarantined for Review**: ${discoveryStats.quarantined}

---

## Key Insights

### Strengths
${this.generateStrengths(kpis, syncFreshness, driftRate)}

### Areas for Improvement
${this.generateImprovements(kpis, syncFreshness, driftRate)}

### Recommendations
${this.generateRecommendations(kpis, syncFreshness, driftRate)}

---

## Trend Analysis

**Period-over-Period Changes**:
- Trust Score: Baseline (first period)
- Risk Avoided: Baseline (first period)
- Drift Rate: Baseline (first period)

*Note: Trend analysis will be available after multiple reporting periods.*

---

## Next Steps

1. Review quarantined agents and approve or reject
2. Investigate any critical sync gaps
3. Address policy violations from high-value agents
4. Schedule follow-up review in 30 days

---

**Report Generated by ORCA Mesh v1.0.0**  
*For questions, contact: ai-ops@acme.com*
`;

    // Save report
    const filename = `executive_summary_${this.formatFileDate(new Date())}.md`;
    await this.saveReport(filename, report);

    logger.info('Executive summary generated', { filename });

    return report;
  }

  /**
   * Generate trust KPIs report
   */
  async generateTrustKPIsReport(periodStart: Date, periodEnd: Date): Promise<string> {
    logger.info('Generating Trust KPIs report');

    const kpis = await trustScoringEngine.computeTrustKPIs(periodStart, periodEnd);
    const trustScores = trustScoringEngine.getAllTrustScores();

    const report = `# Trust KPIs Report

**Period**: ${this.formatDate(periodStart)} to ${this.formatDate(periodEnd)}

## Overall KPIs

- **Trust Score**: ${kpis.trust_score} / 100
- **Risk Avoided**: $${kpis.risk_avoided_usd.toLocaleString()}
- **Sync Freshness**: ${kpis.sync_freshness_percent}%
- **Drift Rate**: ${kpis.drift_rate_percent}%
- **Compliance SLA**: ${kpis.compliance_sla_percent}%
- **Self-Resolution Ratio**: ${(kpis.self_resolution_ratio * 100).toFixed(1)}%
- **ROI**: ${kpis.roi.toFixed(2)}x

## Agent-Level Trust Scores

| Agent ID | Trust Score | Reliability | Policy Adherence | Context Freshness | Risk Exposure |
|----------|-------------|-------------|------------------|-------------------|---------------|
${trustScores.slice(0, 20).map(ts => 
  `| ${ts.agent_id} | ${ts.score} | ${ts.reliability}% | ${ts.policy_adherence}% | ${ts.context_freshness}% | ${ts.risk_exposure}% |`
).join('\n')}

---
*Report generated: ${this.formatDate(new Date())}*
`;

    const filename = `trust_kpis_${this.formatFileDate(new Date())}.md`;
    await this.saveReport(filename, report);

    return report;
  }

  /**
   * Generate sync gaps report
   */
  async generateSyncGapsReport(): Promise<string> {
    logger.info('Generating sync gaps report');

    const gaps = syncAnalyzer.getAllSyncGaps();
    const freshnessMetrics = syncAnalyzer.getAllFreshnessMetrics();

    const report = `# Synchronization Gaps Report

**Generated**: ${this.formatDate(new Date())}

## Summary

- **Total Gaps Detected**: ${gaps.length}
- **Critical**: ${gaps.filter(g => g.severity === 'critical').length}
- **High**: ${gaps.filter(g => g.severity === 'high').length}
- **Medium**: ${gaps.filter(g => g.severity === 'medium').length}
- **Low**: ${gaps.filter(g => g.severity === 'low').length}

## Data Freshness

| Source | Last Sync | Lag (seconds) | Freshness Score | Status |
|--------|-----------|---------------|-----------------|--------|
${freshnessMetrics.map(fm => 
  `| ${fm.source} | ${this.formatDate(fm.last_sync)} | ${fm.lag_seconds}s | ${fm.freshness_score}% | ${fm.is_stale ? '🔴 Stale' : '✅ Fresh'} |`
).join('\n')}

## Detected Gaps

${gaps.slice(0, 50).map(gap => `
### ${gap.gap_type} - ${gap.severity.toUpperCase()}

- **Source**: ${gap.source}
- **Target**: ${gap.target}
- **Detected**: ${this.formatDate(gap.detected_at)}
${gap.lag_ms ? `- **Lag**: ${gap.lag_ms}ms` : ''}
${gap.missing_count ? `- **Missing Records**: ${gap.missing_count}` : ''}
- **Details**: ${JSON.stringify(gap.details, null, 2)}
`).join('\n')}

---
*Report generated by ORCA Sync Analyzer*
`;

    const filename = `sync_gaps_${this.formatFileDate(new Date())}.md`;
    await this.saveReport(filename, report);

    return report;
  }

  /**
   * Save report to file
   */
  private async saveReport(filename: string, content: string): Promise<void> {
    try {
      await fs.mkdir(this.outputDir, { recursive: true });
      const filepath = path.join(this.outputDir, filename);
      await fs.writeFile(filepath, content, 'utf-8');
      logger.info('Report saved', { filepath });
    } catch (error) {
      logger.error('Failed to save report', error as Error, { filename });
    }
  }

  /**
   * Format date for display
   */
  private formatDate(date: Date): string {
    return date.toISOString().split('T')[0];
  }

  /**
   * Format date for filename
   */
  private formatFileDate(date: Date): string {
    return date.toISOString().split('T')[0].replace(/-/g, '');
  }

  /**
   * Generate strengths section
   */
  private generateStrengths(kpis: TrustKPIs, syncFreshness: number, driftRate: number): string {
    const strengths: string[] = [];

    if (kpis.trust_score > 80) {
      strengths.push('- **High Trust Score**: Agents are performing reliably with strong policy adherence');
    }
    if (syncFreshness > 90) {
      strengths.push('- **Excellent Data Freshness**: Data synchronization is performing well');
    }
    if (kpis.self_resolution_ratio > 0.8) {
      strengths.push('- **Strong Self-Healing**: Platform is automatically resolving most issues');
    }
    if (kpis.compliance_sla_percent > 95) {
      strengths.push('- **Compliance Excellence**: Meeting or exceeding compliance SLAs');
    }

    return strengths.length > 0 ? strengths.join('\n') : '- Platform is operating within normal parameters';
  }

  /**
   * Generate improvements section
   */
  private generateImprovements(kpis: TrustKPIs, syncFreshness: number, driftRate: number): string {
    const improvements: string[] = [];

    if (kpis.trust_score < 70) {
      improvements.push('- **Trust Score**: Review agents with low reliability or policy violations');
    }
    if (syncFreshness < 85) {
      improvements.push('- **Data Freshness**: Investigate sync lag issues and optimize sync intervals');
    }
    if (driftRate > 10) {
      improvements.push('- **Configuration Drift**: Address configuration inconsistencies across agents');
    }
    if (kpis.self_resolution_ratio < 0.7) {
      improvements.push('- **Self-Healing**: Enhance self-healing policies to reduce manual interventions');
    }

    return improvements.length > 0 ? improvements.join('\n') : '- No significant areas requiring immediate attention';
  }

  /**
   * Generate recommendations section
   */
  private generateRecommendations(kpis: TrustKPIs, syncFreshness: number, driftRate: number): string {
    return `1. Continue monitoring trust scores weekly
2. Review and update policies quarterly
3. Investigate any agents in quarantine status
4. Optimize sync intervals for better freshness
5. Schedule monthly stakeholder reviews`;
  }
}

/**
 * Singleton instance
 */
export const reportEngine = new ReportEngine();
