# Regional CI/CD Pipeline Configuration
# GitHub Actions matrix jobs for multi-region deployment

name: Multi-Region Deployment

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      regions:
        description: 'Regions to deploy (comma-separated)'
        required: false
        default: 'all'
      strategy:
        description: 'Deployment strategy'
        required: false
        default: 'canary'
        type: choice
        options:
          - canary
          - blue-green
          - rolling

env:
  NODE_VERSION: '20.x'
  REGISTRY: ghcr.io
  IMAGE_NAME: meshos/mesh-kernel

jobs:
  # Pre-deployment validation
  validate:
    name: Validate & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Type check
        run: npm run type-check
      
      - name: Unit tests
        run: npm run test:unit
      
      - name: Integration tests
        run: npm run test:integration
      
      - name: Security scan
        run: npm audit --audit-level=moderate
      
      - name: Build
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  # Build and push container images
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Deploy to regions using matrix strategy
  deploy:
    name: Deploy to ${{ matrix.region }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        region:
          - us-east-1
          - us-west-2
          - eu-west-1
          - eu-central-1
          - ca-central-1
          - me-south-1
          - ap-southeast-1
      fail-fast: false
      max-parallel: 3  # Deploy 3 regions at a time
    
    environment:
      name: ${{ matrix.region }}
      url: https://${{ matrix.region }}.meshos.io
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/
      
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster meshos-${{ matrix.region }} \
            --service meshos-api \
            --force-new-deployment \
            --region ${{ matrix.region }}
      
      - name: Wait for deployment
        run: |
          aws ecs wait services-stable \
            --cluster meshos-${{ matrix.region }} \
            --services meshos-api \
            --region ${{ matrix.region }}
      
      - name: Health check
        run: |
          curl -f https://${{ matrix.region }}.meshos.io/health || exit 1
      
      - name: Update DNS
        if: github.ref == 'refs/heads/main'
        run: |
          aws route53 change-resource-record-sets \
            --hosted-zone-id ${{ secrets.ROUTE53_ZONE_ID }} \
            --change-batch file://dns-update.json

  # Canary deployment
  canary:
    name: Canary Deployment
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.strategy == 'canary' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run canary deployment
        run: node deploy_canary.mjs --image ${{ needs.build.outputs.image-tag }}
      
      - name: Monitor canary metrics
        run: node scripts/monitor-canary.mjs --duration 15m
      
      - name: Analyze canary results
        id: canary-analysis
        run: |
          RESULT=$(node scripts/analyze-canary.mjs)
          echo "result=$RESULT" >> $GITHUB_OUTPUT
      
      - name: Rollback if failed
        if: steps.canary-analysis.outputs.result == 'failed'
        run: node scripts/rollback.mjs --reason "Canary metrics failed"
      
      - name: Promote canary
        if: steps.canary-analysis.outputs.result == 'passed'
        run: node scripts/promote-canary.mjs

  # Smoke tests
  smoke-test:
    name: Smoke Tests - ${{ matrix.region }}
    runs-on: ubuntu-latest
    needs: deploy
    strategy:
      matrix:
        region:
          - us-east-1
          - eu-west-1
          - ap-southeast-1
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run smoke tests
        run: npm run test:smoke -- --region=${{ matrix.region }}
      
      - name: Verify SLA compliance
        run: node scripts/verify-sla.mjs --region=${{ matrix.region }}

  # Notify on completion
  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy, smoke-test]
    if: always()
    steps:
      - name: Slack notification
        uses: slackapi/slack-github-action@v1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Deployment ${{ needs.deploy.result }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚀 *Multi-Region Deployment*\n\n*Status:* ${{ needs.deploy.result }}\n*Commit:* ${{ github.sha }}\n*Regions:* All active regions\n*Smoke Tests:* ${{ needs.smoke-test.result }}"
                  }
                }
              ]
            }

# Deployment configuration per region
regions_config:
  us-east-1:
    cluster: meshos-us-east-1
    service: meshos-api
    taskDefinition: meshos-api-us-east-1
    desiredCount: 5
    loadBalancer: meshos-alb-us-east-1
    
  us-west-2:
    cluster: meshos-us-west-2
    service: meshos-api
    taskDefinition: meshos-api-us-west-2
    desiredCount: 5
    loadBalancer: meshos-alb-us-west-2
    
  eu-west-1:
    cluster: meshos-eu-west-1
    service: meshos-api
    taskDefinition: meshos-api-eu-west-1
    desiredCount: 4
    loadBalancer: meshos-alb-eu-west-1
    
  eu-central-1:
    cluster: meshos-eu-central-1
    service: meshos-api
    taskDefinition: meshos-api-eu-central-1
    desiredCount: 4
    loadBalancer: meshos-alb-eu-central-1
    
  ca-central-1:
    cluster: meshos-ca-central-1
    service: meshos-api
    taskDefinition: meshos-api-ca-central-1
    desiredCount: 2
    loadBalancer: meshos-alb-ca-central-1
    
  me-south-1:
    cluster: meshos-me-south-1
    service: meshos-api
    taskDefinition: meshos-api-me-south-1
    desiredCount: 2
    loadBalancer: meshos-alb-me-south-1
    
  ap-southeast-1:
    cluster: meshos-ap-southeast-1
    service: meshos-api
    taskDefinition: meshos-api-ap-southeast-1
    desiredCount: 3
    loadBalancer: meshos-alb-ap-southeast-1
