name: has-secret
description: Check if a secret is present
inputs:
  secret:
    description: 'The secret value to check'
    required: true
outputs:
  present:
    description: 'Whether the secret is present'
    value: ${{ steps.check.outputs.present }}
runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        if [ -z "${{ inputs.secret }}" ]; then
          echo "present=false" >> $GITHUB_OUTPUT
        else
          echo "present=true" >> $GITHUB_OUTPUT
        fi
